# ****************************************************************
#                           DEPENDENCIES
# ****************************************************************


extra:
   threads: 4


# ****************************************************************
#                              INPUT
# ****************************************************************

# fastq files
input:
   fastq: input/fastq/
   

# ****************************************************************
#                              OUTPUT
# ****************************************************************

# qc_raw_files - quality control on raw fastq files
# ----------------------------------------------------------------
fastqc:
   dir: output/fastqc/


# merge_qc_reports - merge fastqc files from raw fastq files
# ----------------------------------------------------------------
multiqc:
   dir: output/multiqc/